# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'


- task: DotNetCoreCLI@2
  displayName: 'Build 3.1'
  inputs:
    command: 'build'
    arguments: '-c $(buildConfiguration) /p:TargetFramework=netcoreapp3.1'
    projects: '**/*.csproj'
  
- task: DotNetCoreCLI@2
  displayName: 'Build 5.0'
  inputs:
    command: 'build'
    arguments: '-c $(buildConfiguration) /p:TargetFramework=net5.0'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build 6.0'
  inputs:
    command: 'build'
    arguments: '-c $(buildConfiguration) /p:TargetFramework=net6.0'
    projects: '**/*.csproj'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
